<a href="https://colab.research.google.com/github/Huda-Gomaa22/Project-1/blob/main/Feed%20forward%20and%20back%20propagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
print(np.__version__)

2.0.2


In [4]:
import numpy as np
np.random.seed(42)

# -------- Activation Function --------
def tanh(x):
    return np.tanh(x)

# -------- Inputs --------
# Example input (you can change it if previous network had specific values)
x = np.array([[0.6],
              [0.1]])

# -------- Weights Initialization --------
# Random weights in interval [-0.5, 0.5]

# Input → Hidden (2x2 matrix)
W1 = np.random.uniform(-0.5, 0.5, (2, 2))

# Hidden → Output (1x2 matrix)
W2 = np.random.uniform(-0.5, 0.5, (1, 2))

# -------- Biases --------
b1 = 0.5
b2 = 0.7

# -------- Forward Propagation --------

# Hidden layer
z1 = np.dot(W1, x) + b1
a1 = tanh(z1)

# Output layer
z2 = np.dot(W2, a1) + b2
output = tanh(z2)

# -------- Print Results --------
print("Input:")
print(x)

print(" W1:")
print(W1)

print(" W2:")
print(W2)
print("Network Output:")
print(output)

Input:
[[0.6]
 [0.1]]
 W1:
[[-0.12545988  0.45071431]
 [ 0.23199394  0.09865848]]
 W2:
[[-0.34398136 -0.34400548]]
Network Output:
[[0.33893086]]
